################################################ (Template para resolver parametros)
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Helper para resolver parametros, para el Stack de consulta de articulos en tienda.


################################################ (Parametros)
Parameters:
  subnetIDs:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Lista de subnets donde se encuentra la arquitectura

  VpcID:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Id del VPC donde se encuentra la arquitectura

################################################ (Se define un Recurso Falso, ya que es necesario para la definición del template)
Resources:
  NullResource:
    Type: AWS::CloudFormation::WaitConditionHandle


################################################ (Outputs con la resolución de Parametros)
Outputs:
  subnetIDs:
    Value: !Ref subnetIDs
  VpcID:
    Value: !Ref VpcID



