################################################ (Template para resolver parametros)
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Helper para resolver parametros, para el Stack de consulta de articulos en tienda.


################################################ (Parametros)
Parameters:
  # subnetIDs:
  #   Type: AWS::SSM::Parameter::Value<String>
  # utilsIntelixLayerArn: 
  #   Type: AWS::SSM::Parameter::Value<String>    

  secretRespondIO:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Arn de secreto de credenciales para acceder a la base de datos.

  utilsIntelixLayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Arn de capa común con conexiones SQL, a secrets, etc.

  securityGroupLambda:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Security group lambda

  securityGroupProxy:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Security group proxy

  subnetIDs:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Lista de Ids de los grupos de seguridad de cada subnet desde donde
      se puede acceder a la base de datos. Se recomienda al menos dos

  restApiIdInternal:
    Type: AWS::SSM::Parameter::Value<String>
    Description: API Id principal

  countryResource:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Id del recurso del API


################################################ (Se define un Recurso Falso, ya que es necesario para la definición del template)
Resources:
  NullResource:
    Type: AWS::CloudFormation::WaitConditionHandle


################################################ (Outputs con la resolución de Parametros)
Outputs:
  # subnetIDs:
  #   Value: !Ref subnetIDs
  # utilsIntelixLayerArn:
  #   Value: !Ref utilsIntelixLayerArn
  secretRespondIO:
    Value: !Ref secretRespondIO

  utilsIntelixLayerArn:
    Value: !Ref utilsIntelixLayerArn

  securityGroupLambda:
    Value: !Ref securityGroupLambda

  securityGroupProxy:
    Value: !Ref securityGroupProxy

  subnetIDs:
    Value: !Ref subnetIDs

  restApiIdInternal:
    Value: !Ref restApiIdInternal

  countryResource:
    Value: !Ref countryResource


