# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[devate.deploy.parameters]
stack_name = "devate-int-respondIo"
resolve_s3 = true
s3_prefix  = "devate-int-respondIo"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
image_repositories = []
confirm_changeset = true
parameter_overrides = "Environment=\"dev\" integrationMainPath=\"respond-io\""



[qaate.deploy.parameters]
stack_name = "qaate-int-respondIo"
resolve_s3 = true
s3_prefix  = "qaate-int-respondIo"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
image_repositories = []
confirm_changeset = true
parameter_overrides = "Environment=\"qa\"integrationMainPath=\"respond-io\""

[preprodate.deploy.parameters]
stack_name = "preprodate-int-respondIo"
resolve_s3 = true
s3_prefix  = "preprodate-int-respondIo"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
image_repositories = []
confirm_changeset = true
parameter_overrides = "Environment=\"preprod\"integrationMainPath=\"respond-io\""

[prodate.deploy.parameters]
stack_name = "prodate-int-respondIo"
resolve_s3 = true
s3_prefix  = "prodate-int-respondIo"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
image_repositories = []
confirm_changeset = true
parameter_overrides = "Environment=\"prod\"integrationMainPath=\"respond-io\""
