# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[qarespond.sync.parameters]
watch = true
stack_name = "qarespond-int-respondIo"
resolve_s3 = true
s3_prefix  = "qarespond-int-respondIo"
region = "us-west-2"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
image_repositories = []
confirm_changeset = true
parameter_overrides = "Environment=\"qa\" SubnetIds=\"subnet-7e8e1006,subnet-508fe60d\" VpcId=\"vpc-af2b26d7\""


[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[qarespond.deploy.parameters]
stack_name = "qarespond-int-respondIo"
resolve_s3 = true
s3_prefix  = "qarespond-int-respondIo"
region = "us-west-2"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
image_repositories = []
confirm_changeset = true
parameter_overrides = "Environment=\"qa\" SubnetIds=\"subnet-7e8e1006,subnet-508fe60d\" VpcId=\"vpc-af2b26d7\""

[prodrespond.deploy.parameters]
stack_name = "prodrespond-int-respondIo"
resolve_s3 = true
s3_prefix  = "prodrespond-int-respondIo"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
image_repositories = []
confirm_changeset = true
parameter_overrides = "Environment=\"prod\"integrationMainPath=\"respond-io\""
