AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Connection to Initial Contact for Respond.IO

Parameters:
  Environment:
    Type: String

  # secretRespondIO:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Description: Arn de secreto de credenciales para acceder a la base de datos.

  # utilsIntelixLayerArn:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Description: Arn de capa común con conexiones SQL, a secrets, etc.

  # securityGroupLambda:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Description: Security group lambda

  # securityGroupProxy:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Description: Security group proxy

  # subnetIDs:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Description: Lista de Ids de los grupos de seguridad de cada subnet desde donde
  #     se puede acceder a la base de datos. Se recomienda al menos dos

  # restApiIdInternal:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Description: API Id principal

  # countryResource:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Description: Id del recurso del API

  integrationMainPath:
    Type: String
    Description: Ruta base para consulta de articulos de la api compartida
    Default: respond-io

Resources:

  parameterResolver:
    Type: AWS::Serverless::Application
    Properties:
      Location: parameter-resolver.yml
      Parameters:
        utilsIntelixLayerArn: !Sub /${Environment}/ate/parameters/layers/intelixpythonlayerutils 
        secretRespondIO: !Sub /${Environment}/ate/parameters/common/postgres/app_respond_io
        securityGroupLambda: !Sub /${Environment}/ate/parameters/network/default-lambda-security-group
        securityGroupProxy: !Sub /${Environment}/ate/parameters/rds/rdsproxysg
        subnetIDs: !Sub /${Environment}/ate/parameters/network/subnet-ids
        restApiIdInternal: !Sub /${Environment}/ate/parameters/apigateway/restapiidinternal
        countryResource: !Sub /${Environment}/ate/parameters/apigateway/countryresourceinternal

  # Lambdas
  getCustomerDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      # Description:
      CodeUri: functions/msate-get-customer-data/
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          secretRespondIO: !GetAtt parameterResolver.Outputs.secretRespondIO
      VpcConfig:
        SubnetIds: !Split
          - ','
          - !GetAtt parameterResolver.Outputs.subnetIDs
        SecurityGroupIds:
          - !GetAtt parameterResolver.Outputs.securityGroupLambda
          - !GetAtt parameterResolver.Outputs.securityGroupProxy
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !GetAtt parameterResolver.Outputs.secretRespondIO
      Layers:
        - !GetAtt parameterResolver.Outputs.utilsIntelixLayerArn

  # Lambda Logs

  getCustomerDataLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: getCustomerDataFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${getCustomerDataFunction}
      RetentionInDays: 30

  # Api Resource

  getCustomerDataResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !GetAtt parameterResolver.Outputs.restApiIdInternal
      ParentId: !GetAtt parameterResolver.Outputs.countryResource
      PathPart: !Ref integrationMainPath

  CustomerDataResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !GetAtt parameterResolver.Outputs.restApiIdInternal
      ParentId: !Ref getCustomerDataResource
      PathPart: customer

  # Api Method

  customerDataGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !GetAtt parameterResolver.Outputs.restApiIdInternal
      ResourceId: !Ref CustomerDataResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${getCustomerDataFunction.Arn}/invocations

  # Lambda Permissions

  CustomerDataPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref getCustomerDataFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${parameterResolver.Outputs.restApiIdInternal}/*/POST/v1/*/${integrationMainPath}/customer
