AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Connection to Initial Contact for Respond.IO

### Mapeo para decidir el ambiente
Mappings:
  Environments:
    prod:
      Value: PRODUCCION
    qa:
      Value: QA
###


Parameters:
  Environment:
    Type: String
    Default: qa
    AllowedValues:
      - prod
      - qa
    Description: Ambiente de la aplicacion.

##  Ruta base para consulta de articulos de la api compartida con Respond.io
  integrationMainPath:
    Type: String
    Description: Ruta base para consulta de articulos de la api compartida
    Default: respond-io

Resources:

  SecretCommonPostgresTempFC:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub respond/${Environment}/common/postgres/temp/firstContact
      Description: Secret for RDS Proxy connection
      GenerateSecretString:
        SecretStringTemplate: '{"username": "masteradmin", "engine": "aurora-postgresql"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Ambiente
          Value: !FindInMap [Environments, !Ref Environment, Value]

  SecretCommonPostgresOutputParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/respond/parameters/common/cr/secret/postgres/temp
      Type: String
      Value: !Ref SecretCommonPostgresTempFC
      Description: !Sub ${AWS::StackName} SecretCommonPostgresTempFC

  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineVersion: 15.4
      Port: 5432
      EngineMode: provisioned
      MasterUsername: !Sub '{{resolve:secretsmanager:${SecretCommonPostgresTempFC}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${SecretCommonPostgresTempFC}:SecretString:password}}'
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DBSecurityGroup
      PreferredMaintenanceWindow: Sun:06:00-Sun:07:00

  AuroraDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref AuroraDBCluster
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBInstanceClass: db.t3.medium
      Engine: aurora-postgresql
      EnablePerformanceInsights: true
      PerformanceInsightsRetentionPeriod: 31
      MonitoringInterval: 60
      MonitoringRoleArn: !GetAtt DBPostgresMonitoringRoleTempFC.Arn
      PubliclyAccessible: true

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora RDS
      SubnetIds:
        - subnet-7e8e1006
        - subnet-508fe60d

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Aurora RDS
      VpcId: vpc-af2b26d7
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0

  DBPostgresMonitoringRoleTempFC:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - monitoring.rds.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole

  respondApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${AWS::StackName}-respond

  HealthCheckResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref respondApiGateway
      ParentId: !GetAtt respondApiGateway.RootResourceId
      PathPart: health

  HealthCheckMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref respondApiGateway
      ResourceId: !Ref HealthCheckResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HealthCheckLambda.Arn}/invocations"
        IntegrationResponses:
          - StatusCode: '200'
      MethodResponses:
        - StatusCode: '200'
          ResponseModels:
            application/json: Empty

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref respondApiGateway
      StageName: api
    DependsOn:
      - HealthCheckMethod
      - HealthCheckResource

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub ${Environment}-respondApiKey
      Enabled: true
      StageKeys:
        - RestApiId: !Ref respondApiGateway
          StageName: api
    DependsOn:
      - respondApiGateway
      - ApiDeployment

  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref respondApiGateway
          Stage: api
      Description: Usage plan for respond
    DependsOn:
      - ApiKey
      - ApiDeployment

  ApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan
    DependsOn:
      - ApiUsagePlan
      - ApiDeployment

  secretmanagertokenapi:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub /${Environment}/respond/secretmanagertokenapi
      Description: Secret Manager Token API
      SecretString: '{"PRIVATE-TOKEN":"replacement", "ENDPOINT":"replacement"}'

  HealthCheckLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HealthCheckFunction
      Runtime: python3.12
      Handler: lambda_handler.lambda_handler
      CodeUri: functions/health-check-function/
      Timeout: 5
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole

  CustomerDataPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref HealthCheckLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${respondApiGateway}/*/GET/*

