AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Connection to Initial Contact for Respond.IO

### Mapeo para decidir el ambiente
Mappings:
  Environments:
    prod:
      Value: PRODUCCION
    qa:
      Value: QA
###


Parameters:
  Environment:
    Type: String
    Default: qa
    AllowedValues:
      - prod
      - qa
    Description: Ambiente de la aplicacion.

  AccessKeyId:
    Type: String
    Description: Access Key ID for SMTP
    Default: default-access-key-id

  SecretAccessKey:
    Type: String
    Description: Secret Access Key for SMTP
    Default: default-secret-access-key

  Host:
    Type: String
    Description: SMTP Host
    Default: default-smtp-host

  Port:
    Type: String
    Description: SMTP Port
    Default: '587'

  ##  Ruta base para consulta de articulos de la api compartida con Respond.io
  integrationMainPath:
    Type: String
    Description: Ruta base para consulta de articulos de la api compartida
    Default: respond-io

Resources:

  ## Secret Manager Postgres

  SecretCommonPostgresTempFC:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub respond/${Environment}/common/postgres/temp/firstContact
      Description: Secret for RDS Proxy connection
      GenerateSecretString:
        SecretStringTemplate: '{"username": "masteradmin", "engine": "aurora-postgresql"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Ambiente
          Value: !FindInMap
            - Environments
            - !Ref Environment
            - Value

  SecretCommonPostgresOutputParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/respond/parameters/common/cr/secret/postgres/temp
      Type: String
      Value: !Ref SecretCommonPostgresTempFC
      Description: !Sub ${AWS::StackName} SecretCommonPostgresTempFC

  ## Aurora RDS
  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineVersion: 15.4
      Port: 5432
      EngineMode: provisioned
      MasterUsername: !Sub '{{resolve:secretsmanager:${SecretCommonPostgresTempFC}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${SecretCommonPostgresTempFC}:SecretString:password}}'
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DBSecurityGroup
      PreferredMaintenanceWindow: Sun:06:00-Sun:07:00

  AuroraDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref AuroraDBCluster
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBInstanceClass: db.t3.medium
      Engine: aurora-postgresql
      EnablePerformanceInsights: true
      PerformanceInsightsRetentionPeriod: 31
      MonitoringInterval: 60
      MonitoringRoleArn: !GetAtt DBPostgresMonitoringRoleTempFC.Arn
      PubliclyAccessible: true

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora RDS
      SubnetIds:
        - subnet-7e8e1006
        - subnet-508fe60d

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Aurora RDS
      VpcId: vpc-af2b26d7
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0

  DBPostgresMonitoringRoleTempFC:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - monitoring.rds.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole

  ## API Gateway Respond
  respondApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${AWS::StackName}-respond

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref respondApiGateway
      StageName: api
    DependsOn:
      - HealthCheckMethod
      - HealthCheckResource

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub ${Environment}-respondApiKey
      Enabled: true
      StageKeys:
        - RestApiId: !Ref respondApiGateway
          StageName: api
    DependsOn:
      - respondApiGateway
      - ApiDeployment

  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref respondApiGateway
          Stage: api
      Description: Usage plan for respond
    DependsOn:
      - ApiKey
      - ApiDeployment

  ApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan
    DependsOn:
      - ApiUsagePlan
      - ApiDeployment

  secretmanagertokenapi:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub /${Environment}/respond/secretmanagertokenapi
      Description: Secret Manager Token API
      SecretString: '{"PRIVATE-TOKEN":"replacement", "ENDPOINT":"replacement"}'

  RespondApiTokenParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/respond/parameters/common/cr/respond-api-token
      Type: String
      Value: change-me

  ## Lambdas

  ### Health Check Lambda

  HealthCheckResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref respondApiGateway
      ParentId: !GetAtt respondApiGateway.RootResourceId
      PathPart: health

  HealthCheckMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref respondApiGateway
      ResourceId: !Ref HealthCheckResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HealthCheckLambda.Arn}/invocations
        IntegrationResponses:
          - StatusCode: '200'
      MethodResponses:
        - StatusCode: '200'
          ResponseModels:
            application/json: Empty

  HealthCheckLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HealthCheckFunction
      Runtime: python3.12
      Handler: lambda_handler.lambda_handler
      CodeUri: functions/health-check-function/
      Timeout: 5
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole

  HealthCheckPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref HealthCheckLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${respondApiGateway}/*/GET/*

  ### get customer data Lambda

  getCustomerDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: respond-get-customer-data
      Runtime: python3.12
      Handler: lambda_handler.lambda_handler
      CodeUri: functions/respond-get-customer-data/
      Timeout: 30
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:respond/${Environment}/common/postgres/temp/firstContact-*
      Environment:
        Variables:
          secretRespondIO: !Ref SecretCommonPostgresOutputParameter

  getCustomerDataLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: getCustomerDataFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${getCustomerDataFunction}
      RetentionInDays: 30

  getCustomerDataResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref respondApiGateway
      ParentId: !GetAtt respondApiGateway.RootResourceId
      PathPart: customer-data

  customerDataGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref respondApiGateway
      ResourceId: !Ref getCustomerDataResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - LambdaArn: !GetAtt getCustomerDataFunction.Arn

  CustomerDataPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - getCustomerDataFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref getCustomerDataFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${respondApiGateway}/*/GET/*

  ### keyword detection Lambda

  recordConversationMessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: respond-record-conversation
      Runtime: python3.12
      Handler: lambda_handler.lambda_handler
      CodeUri: functions/respond-record-conversation/
      Timeout: 30
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:respond/${Environment}/common/postgres/temp/firstContact-*
      Environment:
        Variables:
          secretRespondIO: !Ref SecretCommonPostgresOutputParameter
          RESPOND_API_TOKEN: !Sub '{{resolve:ssm:${RespondApiTokenParameter}}}'

  recordConversationMessagesLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: recordConversationMessagesFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${recordConversationMessagesFunction}
      RetentionInDays: 30

  recordConversationMessagesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref respondApiGateway
      ParentId: !GetAtt respondApiGateway.RootResourceId
      PathPart: record-conversation

  recordConversationMessagesPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref respondApiGateway
      ResourceId: !Ref recordConversationMessagesResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - LambdaArn: !GetAtt recordConversationMessagesFunction.Arn

  recordConversationMessagesPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - recordConversationMessagesFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref recordConversationMessagesFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${respondApiGateway}/*/POST/*

  ## After hour notification

  afterHourNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: respond-after-hour-notification
      Runtime: python3.12
      Handler: lambda_handler.lambda_handler
      CodeUri: functions/respond-after-hour-notification/
      Timeout: 30
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: ses:SendEmail
              Resource: '*'

  afterHourNotificationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${afterHourNotificationFunction}
      RetentionInDays: 30

  afterHourNotificationResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref respondApiGateway
      ParentId: !GetAtt respondApiGateway.RootResourceId
      PathPart: after-hour-notification

  afterHourNotificationPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref respondApiGateway
      ResourceId: !Ref afterHourNotificationResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - LambdaArn: !GetAtt afterHourNotificationFunction.Arn

  afterHourNotificationPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - afterHourNotificationFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref afterHourNotificationFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${respondApiGateway}/*/POST/*

##  SQS 
  respondSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-respond-sqs-queue
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt respondSqsDLQ.Arn
        maxReceiveCount: 5

  respondSqsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-respond-sqs-dlq



