# TODO: El deployment de la api debe hacerse por consola directamente
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Stack para creacion de api de servicios.

### Mapeo para decidir el ambiente
Mappings:
  Environments:
    prod:
      Value: PRODUCCION
    qa:
      Value: QA
### 

Parameters:
  Networkstack:
    Type: String


  Environment:
    Type: String
    Default: qa
    AllowedValues:
      - prod
      - qa
    Description: Ambiente de la aplicacion.

  ParentStack:
    Type: String

  VpcApiGatewayEndpointId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::VPCEndpoint::Id>

Resources:

  # Respond Api Interna
  respondApiInternal:
    Type: AWS::ApiGateway::RestApi  
    Properties:
      Name: !Sub ${ParentStack}-respond-api-internal
      Policy: !Sub |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": "*",
                "Action": "execute-api:Invoke",
                "Resource": "execute-api:/*"
              },
              {
                "Effect": "Deny",
                "Principal": "*",
                "Action": "execute-api:Invoke",
                "Resource": "execute-api:/*",
                "Condition": {
                  "StringNotEquals": {
                    "aws:SourceVpce": "${VpcApiGatewayEndpointId}"
                  }
                }
              }
            ]
          }


      EndpointConfiguration:
        Types:
          - PRIVATE
        VpcEndpointIds:
          - !Ref VpcApiGatewayEndpointId
      Tags:
        - Key: Ambiente
          Value: !FindInMap
            - Environments
            - !Ref Environment
            - Value



  # Respond Api Internal
  v1ResourceRespondApiInternal:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref respondApiInternal
      ParentId: !GetAtt respondApiInternal.RootResourceId
      PathPart: v1

  respondResourceInternal:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref respondApiInternal
      ParentId: !Ref v1ResourceRespondApiInternal
      PathPart: respond


  respondApiInternalEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/ate/parameters/apigateway/respondapiinternalendpoint
      Type: String
      Value: !Sub ${respondApiInternal}-${VpcApiGatewayEndpointId}.execute-api.${AWS::Region}.amazonaws.com
      Description: Endpoint para el api de servicios.

  restApiIdInternalParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/ate/parameters/apigateway/restapiidinternal
      Type: String
      Value: !Ref respondApiInternal
      Description: Endpoint para el api de servicios.
  
  countryResourceInternalParameters:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/ate/parameters/apigateway/countryresourceinternal
      Type: String
      Value: !Ref countryResourceInternal
      Description: Endpoint para el api de servicios.
  
  storeResourceInternalParameters:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/ate/parameters/apigateway/storeresourceinternal
      Type: String
      Value: !Ref storeResourceInternal
      Description: Endpoint para el api de servicios.



  suiteApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${ParentStack}-msate-suite-api
      Tags:
        - Key: Ambiente
          Value: !FindInMap
            - Environments
            - !Ref Environment
            - Value
        - Key: Proyecto
          Value: ATE
        - Key: TipoApoyoATE
          Value: Indirecto

  v1Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref suiteApi
      ParentId: !GetAtt suiteApi.RootResourceId
      PathPart: v1
    # DependsOn:
    #   - suiteApi
    
  countryResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref suiteApi
      ParentId: !Ref v1Resource
      PathPart: '{country}'
    # DependsOn:
    #   - suiteApi
    #   - v1Resource

  storeResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref suiteApi
      ParentId: !Ref countryResource
      PathPart: '{store}'
    # DependsOn:
    #   - suiteApi
    #   - countryResource

Outputs:

  RestApiId:
    Description: RestApiId del enpoint.
    Value: !Ref suiteApi

  RootResourceId:
    Description: RootResourceId del enpoint.
    Value: !GetAtt suiteApi.RootResourceId

  v1Resource:
    Description: ID del recurso v1.
    Value: !Ref v1Resource

  countryResource:
    Description: ID del recurso Country.
    Value: !Ref countryResource
  
  storeResource:
    Description: ID del recurso Store.
    Value: !Ref storeResource
  